# docker-compose.yml
version: '3.8'
services:
  todoapi:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=aws
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - DB_NAME=todoapi
      - DB_USERNAME=postgres
      - JAVA_OPTS=-Xmx256m -Xms128m  # JVM 메모리 제한
    volumes:
      - /var/log/todoapi:/var/log/todoapi
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3