# src/main/resources/application-aws.yml
spring:
  config:
    import: optional:file:.env.aws[.properties]
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    org.zerock.todoapi: INFO
    root: WARN
  file:
    name: /var/log/todoapi/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

server:
  port: 8080